# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# H2 DATASOURCE
# ===============================
spring.datasource.url=jdbc:h2:mem:camunda;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# CAMUNDA
# ===============================
camunda.bpm.database.type=h2
camunda.bpm.database.schema-update=true
camunda.bpm.job-execution.enabled=true
camunda.bpm.deployment-resource-pattern=classpath*:/processes/*.bpmn
camunda.bpm.default-history-time-to-live=180


# ===============================
# CAMUNDA ADMIN
# ===============================
camunda.bpm.admin-user.id=admin
camunda.bpm.admin-user.password=admin
camunda.bpm.admin-user.firstName=Admin

#camunda.bpm.filter.create=All tasks

# ===============================
# LOG
# ===============================
logging.level.org.camunda.bpm.engine=INFO
